### ISSUE TITLE
Microcontroller performances

### ISSUE THREAD

**Issue by maholli** [WarriorOfWire/CircuitPython_async#6]
First off @WarriorOfWire, absolutely AWESOME work with tasko!! ⭐⭐ 

I wanted to report the performances I'm seeing on the few microcontroller boards I have around. 

- Tested using `test_schedule_rate` from `test_loop.py` (9811f53e3c996496cb7e47d4cd5450ae760bfa19) and [this unittest for CP](https://github.com/mytechnotalent/CircuitPython_Unittest). All boards running https://github.com/adafruit/circuitpython/commit/7df5d74d951f41347502087ef851c19e76c7a2f7
- Throughput reported for maximum tasks achievable before expected tps < actual tps OR tasks miss their scheduled count with the default +- 5 iterations. (duration=1s)

| Board              	| Microcontroller                 	| Task Count 	| Throughput 	|
|--------------------	|---------------------------------	|------------	|------------	|
| Feather M4 Express 	| SAMD51J19 (120 MHz, 192KB SRAM) 	| 17         	| 544 Hz     	|
| PyCubed v05        	| SAMD51J19 (120 MHz, 192KB SRAM) 	| 19         	| 665 Hz     	|
| Feather S2         	| ESP32-S2 (240 MHz, 320KB SRAM)  	| 16         	| 488 Hz     	|

It's very curious to me that the 240 MHz board performs the worst! Any thoughts?

**Comment by kvc0** [comment]
Thanks for this feedback!

So that `Throughput` column should be `Task Count` because that test is kind of funny. The `Throughput` column would have
```
runs/s: 544
runs/s: 665
runs/s: 488
```
respectively.

In fact I've gotten well north of 1000/s on a Feather m4 express on a 3d printer ui application. But as to your question about why one uC is faster than another: I could hand wave about cache locality or instructions per clock or something but the truth of the matter is I only know that this test is pretty degenerate in terms of _semantic context switching_.

If you seek to make S2 faster I'd recommend reading about [flame graphs](http://www.brendangregg.com/flamegraphs.html). Setting up a means to profile in this way would do wonders for CircuitPython performance. I suspect you'd find any meaningful difference in native code timings rather than in python, but flames on either or both would be helpful!

**Comment by maholli** [comment]
Good point @WarriorOfWire! I'll update the table to be more clear.

How/why are you getting DOUBLE the throughput on identical hardware (Feather M4)? Maybe how we're conducting the test? I just threw:

```python
t = TestBudgetScheduler()
t.test_schedule_rate()
```
at the end of `test_loop.py` and ran it as main but this could be a completely wrong way to run a unit test on hardware.

**Comment by kvc0** [comment]
I wasn’t referring to a benchmark, I was referring to an actual project where there are fewer tasks scheduled at higher frequencies and that has no problem reaching 1000 schedules/second. It’s on an older build of circuitpython though, haven’t tried with the tip of main.

**Comment by kvc0** [comment]
Closing stale issue; feel free to reach out if something is wrong!
